### PR TITLE
Remove redux devtools store enhancer, fix #1225

### LINKED ISSUE #1225: [BUG] Not compatible with redux devtools
### Description (Actual behavior)
Currently fe-1 is crashing if the redux devtools browser extension is installed

### How to reproduce
1. Open webpage with extension installed

### Version & Environment
This bug was reproduced on:
- Commit: f78099a4c7c7c3a58acd71f4fddc67251b35ba53

##### Front-ends:
- [x] Fe1-Web (please include browser's names & version)
- [ ] Fe2-Android (please specify if phone or emulation, and Android version)
- [ ] Not applicable

##### Back-ends:
- [ ] Be1-Go
- [ ] Be2-Scala
- [x] Not applicable

### Impact
Application becomes unusable and thus cannot be debugged using the redux devtools

### PR DESCRIPTION
**Pull request by Tyratox**
It turns out that `redux-devtools-extension` and `@redux-devtools/extension` are no longer needed for the redux devtools to work. Unfortunately I did not find this documented anywhere but if you just run the app and check the output of the extension it seems to work.

In addition this PR also disables the `serializableCheck` for `redux-persist` as documented [here](https://redux-toolkit.js.org/usage/usage-guide#use-with-redux-persist).

### CODE REVIEW

File: fe1-web/src/core/redux/GlobalStore.ts [hunk 1]
```diff
@@ -22,14 +22,15 @@ const noopReducer = {
...
-const composedEnhancer = composeEnhancers(applyMiddleware(thunkMiddleware));
 export const store: Store = configureStore({
   reducer: makeRootReducer(noopReducer),
-  enhancers: [composedEnhancer],
+  enhancers: [applyMiddleware(thunkMiddleware)],
+  middleware: (getDefaultMiddleware) =>
+    getDefaultMiddleware({
+      serializableCheck: {
+        ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
+      },
```
Comment (pierluca) [inline fe1-web/src/core/redux/GlobalStore.ts:32]: maybe this was the cause behind some weird problems I remember debugging 😅

**Review by pierluca — DISMISSED** [review]

**Review by Xelowak — APPROVED** [review]
LGTM

**Review by pierluca — APPROVED** [review]
