### PR TITLE
Verify the sender of Rollcall create/open/close

### LINKED ISSUE #1777: [BUG] No verification that only organizer can create/open/close rollcall
### Description (Actual behavior)
On the be1-go backend, there is no verification that only organizer can create/open/close a rollcall.
Anyone can send theses messages (using a modified frontend) and the go backend will accept them.

### Expected behavior
There should have a verification of the public key and deny any rollcall create/open/close if not from an organizer.

### How to reproduce
1. Create a Lao with client1 (organizer)
2. Join the Lao with client2 (with a modified frontend that allow sending the messages)
3. Create/open/close a Rollcall with client2
4. See no error (expected to fail)

### Version & Environment
This bug was reproduced on:
- Commit: 8f30905

##### Front-ends:
- [ ] Fe1-Web (please include browser's names & version)
- [ ] Fe2-Android (please specify if phone or emulation, and Android version)
- [x] Not applicable

##### Back-ends:
- [x] Be1-Go
- [ ] Be2-Scala
- [ ] Not applicable

### Workaround
The scala backend doesn't seem to be vulnerable to the same problem.

### Impact
Anyone can maliciously create a new rollcall and add many PoP token.

### Possible root cause
No verification that the sender of a rollcall create/open/close is the organizer.

### PR DESCRIPTION
**Pull request by arnauds5**
closes #1777

There was no verification that Rollcall create/open/close were only accepted from an organizer.
If theses messages were send by anyone, the go backend was accepting them.

This PR add a verification for each of theses messages and deny them if it was not send by an organizer.
An helper function was made using the existing code of the election#setup verificaiton.

### CODE REVIEW

**Review by sgueissa — DISMISSED** [review]
Everything looks good for me

File: be1-go/channel/lao/lao.go [hunk 1]
```diff
@@ -768,3 +775,28 @@ func (c *Channel) extractLaoID() string {
...
 	return string(prevID) == r.id
 }
+
+// checkIsFromOrganizer is a helper method which validates that the message's
+// sender is the organizer. Return an error if it failed or if it's false,
+// return nil if it was from the organizer.
+func (c *Channel) checkIsFromOrganizer(msg message.Message) error {
+	senderBuf, err := base64.URLEncoding.DecodeString(msg.Sender)
+	if err != nil {
+		return xerrors.Errorf(keyDecodeError, err)
```
Comment (MariemBaccari) [inline be1-go/channel/lao/lao.go:785]: Is there a reason why this is built using `xerrors.Errorf` not as an `amswer.NewErrorf` like the other errors returned ?

**Review by MariemBaccari — APPROVED** [review]
Good job ! The fix looks good to me. I just have a slight question.

File: be1-go/channel/lao/lao.go (hunk 1 above)
Comment (arnauds5) [reply be1-go/channel/lao/lao.go]: It was because this function was created using some existing code.
After reading answer/error.go, I just found that there are some functions with the error code already inside,
such as `answer.NewInvalidMessageFieldError` and `answer.NewAccessDeniedError`.

**Review by MariemBaccari — APPROVED** [review]
