### PR TITLE
Cast Vote Fragment tests + minor fixes

### LINKED ISSUE #1103: [BUG] Unselecting a ballot option crashes the app
### Description (Actual behavior)
When on the cast vote screen selecting and then unselecting an option make the app crash

### Expected behavior
We expect to be able to select and unselect an option and we expect the app not to crash

### How to reproduce
1. Open an election
2. Select an item and unselect it
3. See crash

### Version & Environment
This bug was reproduced on:
- Commit: [1580929](https://github.com/dedis/popstellar/commit/15809294d7eb092796dcdbcd57d0f1ca664f70c3)

##### Front-ends:
- [ ] Fe1-Web (please include browser's names & version)
- [x] Fe2-Android (please specify if phone or emulation, and Android version)
- [ ] Not applicable

##### Back-ends:
- [ ] Be1-Go
- [ ] Be2-Scala
- [x] Not applicable

##### Environment (as applicable):
 - Device: [e.g. Pixel 4 emulator on Windows 10]

### Workaround
Not unselecting an item. Changing item is fine too.

### Impact
Being able to unselect an item is not a very useful feature for now, so in term of feature usage prevention, little. The fact it crashes the app is quite problematic as a user might tap twice by error

### Possible root cause
Since #1052, we take the first vote of the list without checking that the list is non-empty

### PR DESCRIPTION
**Pull request by Warhedgehog**
This PR adds basic UI tests for the `CastVoteFragment` 
It also fixes #1103 and #1102

### CODE REVIEW

**Review by Tesa27 — APPROVED** [review]
LGTM

File: fe2-android/app/src/main/java/com/github/dedis/popstellar/utility/Constants.java [hunk 1]
```diff
@@ -19,4 +19,8 @@ public class Constants {
 
   /** Using the Resources class constant would require a min API of 29 */
   public static final int ID_NULL = 0;
+
+  public static final float DISABLED_ALPHA = 0.4f;
```
Comment (ahominal) [inline fe2-android/app/src/main/java/com/github/dedis/popstellar/utility/Constants.java:23]: Quick question, why alpha?

**Review by ahominal — APPROVED** [review]
Seems good, didn't sport anything. Just had a questions

File: fe2-android/app/src/main/java/com/github/dedis/popstellar/utility/Constants.java (hunk 1 above)
Comment (Warhedgehog) [reply fe2-android/app/src/main/java/com/github/dedis/popstellar/utility/Constants.java:23]: It's the terminology for transparentness

File: fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/detail/event/election/adapters/CastVoteViewPagerAdapter.java [hunk 2]
```diff
@@ -119,8 +120,9 @@ public int getItemCount() {
   private boolean checkEachQuestion() {
     List<Integer> allVotes = mLaoDetailViewModel.getCurrentElectionVotes().getValue();
     if (allVotes != null) {
+      if (allVotes.size() < getItemCount()) return false;
```
Comment (jbsv) [inline fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/detail/event/election/adapters/CastVoteViewPagerAdapter.java:123]: why don't we just return false if allVotes.isEmpty() here  ? Instead of using a hard coded value -1 ?

**Review by GabrielFleischer — APPROVED** [review]
LGTM
