### PR TITLE
Error handling

### LINKED ISSUE #1449: Unclear error messages for some actions on Android
### Description (Actual behavior)
- This happens when the organizer opens a roll call X, closes X, opens a roll call Y, closes Y, and then tries to reopen X. The exception is the following:

> E/RollCallFragment: Could not open the rollcall
> [An error response was replied by the server
> Error -4 - invalid message field: failed to publish: failed to handle publish message: failed to process message: failed to process action 'roll_call#reopen': The field `opens` does not correspond to the id of the previous roll call message]
> com.github.dedis.popstellar.utility.error.JsonRPCErrorException: Error -4 - invalid message field: failed to publish: failed to handle publish message: failed to process message: failed to process action **'roll_call#reopen'**: The field `opens` does not correspond to the id of the previous roll call message

A second error happens when a user wants to cast a vote without having a pop token. There the application throws a generic 'Could not send the vote', which can be misleading.

### Expected behavior
Both are desired behaviours, however the errors displayed on the fe to the user should be more informative of the motivation (e.g. 'Cannot reopen a roll call right after having closed another one').

### How to reproduce
In the following video there's an execution flow that shows the error message on the reopening:
[reopening.webm](https://user-images.githubusercontent.com/83547952/223569326-ade3d97e-d68b-4a34-8e6c-7b72b36c15d5.webm)

For the election, simply go on a open election without pop token and try to cast a vote.

### Version & Environment
This was reproduced on this [commit](https://github.com/dedis/popstellar/tree/bc23763f593c18dc39a0cf5446bc6352ac71582e).

##### Front-ends:
- [ ] Fe1-Web
- [X] Fe2-Android
- [ ] Not applicable

##### Back-ends:
- [ ] Be1-Go
- [ ] Be2-Scala
- [X] Not applicable

### Impact
No impact in terms of functionality.

### PR DESCRIPTION
**Pull request by matteosz**
This PR resolves #1449.

Changes
---------

- Remove the possibility of reopening old roll calls (i.e. closed roll calls before the last closed one). Previously upon reopening a server error message was thrown
- Handled error message for casting a vote with no valid pop token. Previously, the user could enter in the cast vote fragment and then receive a generic message error
- Fixed the color of some text in election setup for dark mode

### CODE REVIEW

File: fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/lao/event/rollcall/RollCallFragment.java [hunk 1]
```diff
@@ -206,7 +207,24 @@ private void setUpStateDependantContent() {
     boolean isOrganizer = laoViewModel.isOrganizer();
 
     binding.rollCallFragmentTitle.setText(rollCall.getName());
-    binding.rollCallManagementButton.setVisibility(isOrganizer ? View.VISIBLE : View.GONE);
+    try {
+      // If the roll call is not closed management button is open or close
+      // Then it should be visible only to the organizer
+      // However, if isOrganizer but the roll call is closed then the button is
+      // reopen, however this is a valid action only if this is the last closed roll call
+      if (isOrganizer
```
Comment (simone-kalbermatter) [inline fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/lao/event/rollcall/RollCallFragment.java:215]: It would be good to extract some of the checks from the if() here as it gets a bit unclear what is actually checked.

**Review by simone-kalbermatter — CHANGES_REQUESTED** [review]
Nice ways to implement these checks! Just 2 comments.

File: fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/lao/event/rollcall/RollCallFragment.java (hunk 1 above)
Comment (matteosz) [reply fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/lao/event/rollcall/RollCallFragment.java:215]: Yes, you're right, I'll try to simplify the readability

File: fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/lao/event/rollcall/RollCallFragment.java [hunk 2]
```diff
@@ -206,7 +207,24 @@ private void setUpStateDependantContent() {
...
+              || (rollCall.isClosed()
+                  && rollCallRepo
+                      .getLastClosedRollCall(laoViewModel.getLaoId())
+                      .equals(rollCall)))) {
+        binding.rollCallManagementButton.setVisibility(View.VISIBLE);
+      } else {
+        throw new NoRollCallException("");
+      }
+    } catch (NoRollCallException e) {
+      binding.rollCallManagementButton.setVisibility(View.GONE);
```
[the remark this answers is not in the document]
Comment (matteosz) [reply fe2-android/app/src/main/java/com/github/dedis/popstellar/ui/lao/event/rollcall/RollCallFragment.java:226]: Sure, I'll add a test for that!

**Review by simone-kalbermatter — APPROVED** [review]
LGTM, nice clean work!

**Review by Warhedgehog — APPROVED** [review]
LGTM
